### ISSUE TITLE
Questions/comments

### ISSUE THREAD

**Issue by jgabry** [betanalpha/stan_intro#4]
Some questions and comments not addressed in any of the PRs:
- [ ] In **Stochastic Representations of Probability Distributions** (3.4)
  Is the equation for recovering expectations (lim_{N \to \infty} ...) missing a summation?
- [ ] In **Concentration of Measure** (4.1)
  From the context I don't think it's immediately clear to the reader exactly what "these two contributions" is referring to in the sentence beginning with
  
  > Consequently the integrand, which is the _product_ of these two contributions, concentrates in a singular...
- [ ] In **Big Worlds and Small Worlds** (7.2), I'm not sure how to fix the sentence below. Do you mean to say that it only has some probability of containing the latent DGP?
  
  > Because any small world is likely to be only a shallow approximation of reality, for example, it is probability to contain the latent data generating process (Figure 15b).

**Comment by betanalpha** [comment]
Addressed in 9d3204b4cc833186cc61d47a566219b168e27991.
