### ISSUE TITLE
stan intro copyedits

### ISSUE THREAD

**Issue by mitzimorris** [betanalpha/stan_intro#8]
Ongoing set of comments from reading through this.

section "Our Strategy" 4th paragraph:  

> In this introduction we will not ignore the abstractions of probability theory. As with more formal treatments we will instead being by discussion the abstract theory

"we will instead being" should be:   "we will instead begin by"
"by discussion the abstract" should be either:  "by discussing the abstract"  or "by discussion of"

final sentence in same paragraph:

> As we develop representations we’ll discuss more and more specific examples to develop as much intuitive context as can 

"as can" should be:  "as we can" or "as possible"

**Comment by mitzimorris** [comment]
> 1.2 Representations of Logical Models
> Logical models provide a very abstract, and hence very genetic,

"genetic" or "generic"?

**Comment by maswiebe** [comment]
Section 4.3.6:

> For example the statement
target += normal_lpdf(y | mu, sigma);
would be replaced by the sparser statement
y ~ normal(y | mu, sigma);

Should the latter be `y ~ normal(mu, sigma)`?

**Comment by betanalpha** [comment]
Thanks for the comments.  This document is no longer being maintained -- for my currently supported writing see https://betanalpha.github.io/writing/.
